server:
   port: 80
   servlet:
      context-path: /
   tomcat:
      uri-encoding: UTF-8
      max-threads: 800
      min-spare-threads: 30

log:
   operation: true

logging:
   config: classpath:logback-spring.xml
   path: /var/log/pestle.log

mybatis:
   configLocation: classpath:mybatis/mybatis-config.xml
   mapperLocations: mybatis/**/*Mapper.xml
   typeAliasesPackage: org.cloud.chiron.system.model

spring:
   redis:
      host: db.cloud.org
      port: 6379
      jedis:
         pool: 
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
      timeout: 0
   rabbitmq:
      host: db.cloud.org
      port: 5672
      username: rabbitmq
      password: rabbitmq
      publisher-confirms: true
      virtual-host: /
      listener:
         concurrency: 10
         max-concurrency: 20
         prefetch: 5
   thymeleaf:
      mode: HTML
      encoding: UTF-8
      cache: false
   profiles:
      active: druid
   data:
      redis:
         repositories:
            enabled: false

pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
   